// CHATS
export const ADD_CHAT = 'ADD_CHAT';
export const ADD_CHAT_ROOMID = 'ADD_CHAT_ROOMID';
export const LOAD_CHATS = 'LOAD_CHATS';
export const JOIN_CHAT = 'JOIN_CHAT';
export const LEAVE_CHAT = 'LEAVE_CHAT';

// CHAT
export const ADD_INCOMING_MESSAGE = 'ADD_INCOMING_MESSAGE';
export const POST_MESSAGE = 'POST_MESSAGE';
export const SHOW_OTHERS_TYPING = 'SHOW_OTHERS_TYPING';
export const SHOW_OTHERS_TYPING_STOPPED = 'SHOW_OTHERS_TYPING_STOPPED';
